language: node_js

node_js:
  - "10.8.0"
os:
  - linux

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn global add lerna rimraf typescript
  - yarn bootstrap

jobs:
  include:
    - stage: tests
      script:
        - yarn test
    - stage: npm release
      deploy:
        - provider: script
          script: yarn release
          skip_cleanup: true
          on:
            tags: true
