language: node_js

node_js:
  - 'stable'
os:
  - linux

cache:
  yarn: true
  directories:
    - node_modules

install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install

script:
  - yarn test
