language: node_js

node_js:
    - 'stable'
os:
    - linux

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn global add lerna
    - lerna bootstrap

script:
    - lerna run test

deploy:
    provider: script
    script: 'yarn run release'
    skip_cleanup: true
    on:
        tags: true
