language: node_js

node_js:
    - "10.8.0"
os:
    - linux

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn global add lerna rimraf typescript
    - lerna bootstrap

matrix:
    include:
        - name: "React Pipeline"
          env: PACKAGE_LOCATION=packages/react
        - name: "Vue Pipeline"
          env: PACKAGE_LOCATION=packages/vue

script:
    - cd $PACKAGE_LOCATION
    - yarn test
    - yarn build

deploy:
    provider: script
    script: "yarn run release"
    skip_cleanup: true
    on:
        tags: true
