# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
    working_directory: ~/auto
    docker:
        - image: circleci/node:latest-browsers

jobs:
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: install
                  command: yarn install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules

    release:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/auto
            - run:
                  name: Release
                  command: yarn run release

workflows:
    version: 2
    build_and_release:
        jobs:
            - install:
                  filters:
                      tags:
                          only: /.*/

            - release:
                  requires:
                      - install
                  filters:
                      branches:
                          only:
                              - master
