name: Build

on: [push]

jobs:
    release:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Skip CI
          uses: veggiemonk/skip-commit@master
          env:
              COMMIT_FILTER: skip ci
        - name: Prepare repository
            env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
            run: |
                git checkout "${GITHUB_REF:11}"
                git remote rm origin
                git remote add origin "https://$GH_TOKEN@github.com/FrontendRangers/platoon.git"
                git fetch origin
                git branch --set-upstream-to origin/master
            - name: Create Release
                env:
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                run: |
                    git remote -v
                    yarn
                    yarn build
                    yarn release
